version: '3'

services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command:
      - start-dev
    restart: always
    links:
      - postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin1234
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password

volumes:
  postgres_data:
      driver: local